### ISSUE TITLE
Help me trevor

### ISSUE THREAD

**Issue by Luke-Tseng** [LukeGTseng/Fraction-Calculator#1]
I need help with multiplying and dividing

**Comment by AwpData** [comment]
Ok here is some example coding of what you could try to divide:

public static String DivideFormula(int F1numerator, int F2numerator, int F1denominator, int F2denominator) {		
int tempnum = F2numerator; // In order to prevent the denominator from being the numerator and denominator
		F2numerator = F2denominator;
		F2denominator = tempnum;
		int topline = F1numerator * F2numerator;
		int bottomline = F1denominator * F2denominator;
		return (topline + "/" + bottomline);

**Comment by Luke-Tseng** [comment]
trevor can you hit me up with some subtraction example code?

**Comment by Luke-Tseng** [comment]
don't need it anymore. i fixed it.
